id = "bean-lang"
name = "Bean Lang"
version = "0.0.1"
schema_version = 1
authors = ["Team Bean <dev.team.bean@gmail.com>"]
description = "Extension for BeanLang"
repository = "https://github.com/NIK-Pro-coder/beanlang"
